### PR TITLE
convert F5 cookie decoder to a check and fix newly-introduced bugs

### PR DESCRIPTION
**Pull request by jcran**
Converted, needs a quick check / test to verify that it resolves the issues i introduced over the weekend. Can you confirm @m-q-t?

### CODE REVIEW

**Comment by jcran** [comment]
Handling of a F5 where no cookie is set: 
image

**Comment by jcran** [comment]
Handling a provided cookie: 
image

**Comment by jcran** [comment]
Issue details 

image

**Comment by jcran** [comment]
Note that i bumped this up to a 'low' severity - and set the only-pool case back to no-issue-created, as discussed today. Also all info is now stored on the original entity as part of the check, just in case it's helpful.

**Review by shpendk — APPROVED** [review]
Looks good, but I'd recommend deleting the issue at `lib/issues/f5_bigip_cookie_decoder.rb` since it will try to start a task named `f5_bigip_cookie_decoder` and fail.

**Comment by jcran** [comment]
Will do, good catch @shpendk

**Comment by m-q-t** [comment]
Tested against ~ 15 different hosts and works great. Awesome job.

**Pull request merged**
