### PR TITLE
allows bootstrap to send a custom workflow

### PR DESCRIPTION
**Pull request by jcran**
This PR makes any bootstrap create a new workflow and set it as the workflow associated with the scan. this enables fully-custom workflows to be specified at bootstrap time.

### CODE REVIEW

**Comment by jcran** [comment]
Example bootstrap message: 
`{
	"id": "intrigueio",
	"type": "Intrigue::Collections::UserCollection",
	"system_config": "default",
	"projects": [{
		"name": "intrigueio",
		"collection": "intrigueio",
		"collection_uuid": "2e54af8b-0245-4cf2-a5f0-5dae5a22b254",
		"task_name": "create_entity",
		"task_options": [],
		"project_handlers": ["data.intrigue.io"],
		"project_options": [],
		"vulnerability_checks_enabled": true,
		"use_standard_exceptions": false,
		"allowed_namespaces": [],
		"auto_enrich": true,
		"workflow_name": "intrigueio_custom_collection_kljh123",
		"workflow_definition": {
			"AwsS3Bucket": [{
				"task": "aws_s3_find_listable_objects"
			}, {
				"task": "aws_s3_put_file"
			}]
		},
		"seeds": [{
			"entity": "Domain#intrigue.io"
		}]
	}]
}`

**Comment by m-q-t** [comment]
Latest commit fixes an issue in which the workflows retrieved from the database were not being concatenated in the return array thus throwing an `InvalidWorkflowError` due to the workflow not being found.

**Comment by m-q-t** [comment]
here is the bootstrap json I used to validate this:

```
{
	"id": "maxim",
	"type": "Intrigue::Collections::UserCollection",
	"system_config": "default",
	"projects": [{
		"name": "maxim12345",
		"collection": "maxim",
		"collection_uuid": "",
		"task_name": "create_entity",
		"task_options": [],
		"project_handlers": [""],
		"project_options": [],
		"vulnerability_checks_enabled": true,
		"use_standard_exceptions": false,
		"allowed_namespaces": [],
		"auto_enrich": true,
		"workflow_name": "intrigueio_maxim_12345",
		"workflow_definition": {
			"Domain": [{
					"task": "subfinder"
				},
				{
					"task": "search_crt",
					"options": [{
						"extract_patterns": true
					}]
				}
			]
		},
		"seeds": [{
			"entity": "Domain#intrigue.io"
		}]
	}]
}
```

(very similar to the above except I was verifying that options would work as well)

**Comment by jcran** [comment]
Thanks for testing @m-q-t, merging to develop

**Pull request merged**
