### PR TITLE
COR-78 Subdomain Scraper Task - PassiveTotal/RiskIQ

### PR DESCRIPTION
**Pull request by chowdud**

### CODE REVIEW

**Review by shpendk — CHANGES_REQUESTED** [review]
Running `search_riskiq` against the domain `intrigue.io` gives the following error:
```
86f14d3222beefa37a","created_at":1628171858.451404,"enqueued_at":1628171858.4516377},"jobstr":"{\"retry\":true,\"queue\":\"task\",\"class\":\"Intrigue::Task::SearchRiskIQ\",\"args\":[842],\"jid\":\"9d3aa986f14d3222beefa37a\",\"created_at\":1628171858.451404,\"enqueued_at\":1628171858.4516377}"}
15:57:42 worker.1 | 2021-08-05T13:57:42.949Z pid=33765 tid=jjl WARN: NoMethodError: undefined method `each' for nil:NilClass
15:57:42 worker.1 | 2021-08-05T13:57:42.949Z pid=33765 tid=jjl WARN: /mnt/hgfs/GitHub/intrigue-core/lib/tasks/search_riskiq.rb:68:in `do_domains'
15:57:42 worker.1 | /mnt/hgfs/GitHub/intrigue-core/lib/tasks/search_riskiq.rb:116:in `do_riskiq'
15:57:42 worker.1 | /mnt/hgfs/GitHub/intrigue-core/lib/tasks/search_riskiq.rb:31:in `run'
15:57:42 worker.1 | /mnt/hgfs/GitHub/intrigue-core/lib/tasks/base.rb:161:in `perform'
15:57:42 worker.1 | /home/ubuntu/.rbenv/versions/2.7.2/gemsets/core/gems/sidekiq-6.2.1/lib/sidekiq/processor.rb:196:in `execute_job'

```

Can you please test all edge cases for both tasks? Thanks!

**Comment by shpendk** [comment]
Hi @chowdud 

Still getting the same error as before so the bug is not fixed. Also, why did you modify `lib/tasks/enrich/ssl_certificate.rb`? How is that related to these tasks?

**Comment by chowdud** [comment]
Did you generate a new set of credentials? The time.parse error originated from the ssl certificate enrich task, hence the change to the file.

**Comment by shpendk** [comment]
Can you open a new PR based on the latest code? And if you need to make changes to `enrich/ssl_certificate` please document them in detail. thanks!

**Pull request closed without merging**
