### PR TITLE
CAA in-depth checking

### PR DESCRIPTION
**Pull request by jen140**
Added a check of the validity of the CAA record.
It gets Organization name from the issuer in the domain's certificate and compares it to all the Organization names taken from all the domains in the CAA response.

Also added minor changes to a few checks.

### CODE REVIEW

**Review by shpendk — CHANGES_REQUESTED** [review]
as discussed, the certificate verification must be adapted. Marking this as `request changes` until we figure that out

**Comment by jcran** [comment]
>> certificate verification must be adapted

Can you clarify this?

**Comment by jen140** [comment]
Currently the process extracts the certificate issuer organization of the website that's being checked, then we do a https requests  to all the domains from the CAA response and check if the organization is the same. 

In some cases (like facebook) this doesn't really work(and an invalid CAA issue would be generated),
facebook.com has an Organization of their issuer as "DigiCert Inc" and only one CAA response of digicert.com
digicert.com has their certificate issued for "DigiCert, Inc." (note the "," and ".")

The idea to fix that was to bundle CA certificates and keep them updated (mozilla ca could be used for that) and have an independent go service provide the required details when necessary but more urgent tasks came in.

**Comment by shpendk** [comment]
Closing this in favor of a new PR, once we clear the blocker.

**Pull request closed without merging**
